export const LOADING_REPO = 'LOADING_REPO';
export const SEARCH_REPO_SUCCESS = 'SEARCH_REPO_SUCCESS';
export const SEARCH_REPO_FAILURE = 'SEARCH_REPO_FAILURE';

export const LOADING_USER = 'LOADING_USER';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';
